const test_suite = {
	"kernel/scope/nonlocal":	require("!!raw-loader!./kernel/scope/nonlocal.py").default,
	"kernel/scope/global":	require("!!raw-loader!./kernel/scope/global.py").default,
	"kernel/op/walrus":	require("!!raw-loader!./kernel/op/walrus.py").default,
	"kernel/op/unary":	require("!!raw-loader!./kernel/op/unary.py").default,
	"kernel/op/or":	require("!!raw-loader!./kernel/op/or.py").default,
	"kernel/op/not":	require("!!raw-loader!./kernel/op/not.py").default,
	"kernel/op/is":	require("!!raw-loader!./kernel/op/is.py").default,
	"kernel/op/ibin":	require("!!raw-loader!./kernel/op/ibin.py").default,
	"kernel/op/cmp":	require("!!raw-loader!./kernel/op/cmp.py").default,
	"kernel/op/bin":	require("!!raw-loader!./kernel/op/bin.py").default,
	"kernel/op/asignbin":	require("!!raw-loader!./kernel/op/asignbin.py").default,
	"kernel/op/and":	require("!!raw-loader!./kernel/op/and.py").default,
	"kernel/match/classes":	require("!!raw-loader!./kernel/match/classes.py").default,
	"kernel/import/index":	require("!!raw-loader!./kernel/import/index.py").default,
	"kernel/fct/index":	require("!!raw-loader!./kernel/fct/index.py").default,
	"kernel/ctrlflow/continue":	require("!!raw-loader!./kernel/ctrlflow/continue.py").default,
	"kernel/ctrlflow/break":	require("!!raw-loader!./kernel/ctrlflow/break.py").default,
	"kernel/async/index":	require("!!raw-loader!./kernel/async/index.py").default,
	"core/int/op":	require("!!raw-loader!./core/int/op.py").default,
	"core/float/op":	require("!!raw-loader!./core/float/op.py").default,
}
export default test_suite